public class FileMimeTypes {

    public static final string CSV = 'text/csv';

    public static final string GOOGLE_DOC = 'application/vnd.google-apps.document';

    public static final string GOOGLE_FORM = 'application/vnd.google-apps.form';

    public static final string GOOGLE_SHEET = 'application/vnd.google-apps.spreadsheet';

    public static final string JPEG = 'image/jpeg';

    public static final string PDF = 'application/pdf';

    public static final string PNG = 'image/png';

    public static final string TEXT = 'text/plain';

    public static final string ZIP = 'application/x-zip-compressed';
}
