#!/bin/bash -x
echo "Starting Dev Environment"
echo "authenticating to devhubtrial2"
sfdx force:auth:jwt:grant -i 3MVG9mclR62wycM2eQwLGugMMMWe5zQvP33hzD_0yCIWytEEI73gZsu8wtNti51PfxuTT_p0F6BrRyAeCVQjN -u alexdevhubtrial2@edelstein.org -f ~/dev/certificates/server.key --setdefaultdevhubusername
echo "creating a new scratch org"
sfdx force:org:create -a $1 -f config/project-scratch-def.json 
echo "install testing environment"
sfdx force:lightning:test:install -u $1
echo "pushing project to scratch org"
sfdx force:source:push -u $1
echo "upload test fixture data"
sfdx force:data:tree:import -u $1 -f data/Strategy__c.json 
echo "get web url for manual open"
sfdx force:org:open -r -u $1