/** 
 *  Return First N Records Flow Action
 * 
 *  This invocable flow action is designed to take a collection of record and a numeric count (N)
 *  and return the first N records from the collection.
 * 
 *  This is useful when you want to programatically decide how many records you need unlike having to provide a fixed value in actions such as the flow Sort element.
 * 
 *  Eric Smith - 4/23/23 - v1.0.0
 *      Initial Release
 * 
 * 
**/ 
global inherited sharing class ReturnFirstNRecords {
    
    public ReturnFirstNRecords() {

    }
}